# Generated by Django 4.0.6 on 2022-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='elective',
            field=models.CharField(choices=[('da', 'da'), ('ne', 'ne')], max_length=2),
        ),
    ]
