# Generated by Django 4.0.6 on 2022-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_elective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PROFESSOR', 'professor'), ('STUDENT', 'student')], max_length=20),
        ),
    ]
